### ISSUE TITLE
Annotation Request for Gateway

### ISSUE THREAD

**Issue by DrMxrcy** [kubesail/kubesail-agent#32]
Requesting some Annoations For Specific Apps. 
```

    Nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 1G
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.org/websocket-services: immich-server
    
```

Here's an Example I am working on for Immich
    
 ```
   
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: immich-server
  labels:
    app: immich-server
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 1G
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.org/websocket-services: immich-server
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - "{{ APP_URL }}"
  rules:
  - host: "{{ APP_URL }}"
    http:
      paths:
      - backend:
          service:
            name: immich-server
            port:
              name: api-endpoint
        path: /api(/|$)(.*)
        pathType: Prefix

```
